# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SVN-Access
version:      0.10
version_from: lib/SVN/Access.pm
installdirs:  site
author:
  - Michael Gregorowicz <mike@mg2.org>

license:      perl
abstract:     Perl extension to manipulate SVN Access files

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
requires:
